# Import Libraries

In [1]:
import pandas as pd

In [14]:
df = pd.read_csv(r"E:\\NLP\\IMDB Dataset.csv\\IMDB Dataset.csv",nrows = 100)

In [15]:
df

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
..                                                ...       ...
95  Daniel Day-Lewis is the most versatile actor a...  positive
96  My guess would be this was originally going to...  negative
97  Well, I like to watch bad horror B-Movies, cau...  negative
98  This IS the worst movie I have ever seen, as w...  negative
99  I have been a Mario fan for as long as I can r...  positive

[100 rows x 2 columns]

In [16]:
df['review'] = df['review'].str.lower()

In [17]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. <br /><br />the...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

# Removing HTML Tags

* The re library in Python is the built-in module for working with regular expressions (regex). Regular expressions are patterns that provide a powerful way to search, match, and manipulate text.

* In this class remove_html_tags is applied on the text and the in the next step the pattern stores the words which has matching expression such as '<.*?>' in the text and then after processing it removes the expressions and return the text with an empty string

In [18]:
import re  #Regular Expressions
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

* Now by applying the below code the html tags get removed provide an empty string by replacing expression.

In [19]:
df['review'] = df['review'].apply(remove_html_tags)

In [20]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. the filming tec...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

# Removal of url

* Now a class is applied on text named remove_url it also performs same as html tags removal and returns text in plain form.

In [21]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www.\.\S+')
    return pattern.sub(r'', text)

In [22]:
df['review'] = df['review'].apply(remove_url)

In [23]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. the filming tec...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

# Removal of Punctuations

* in the below code 
  string: Provides constants, classes, and functions for string operations; 
  time: Provides functions to work with time-related operations (used for delays, timestamps, etc.).
* string.punctuation is a constant that contains a string of all printable punctuation characters.

In [24]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [25]:
exclude = string.punctuation

In [26]:
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))

df['review'] = df['review'].apply(remove_punc)

In [27]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production the filming tech...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically theres a family where a little boy j...  negative
4   petter matteis love in the time of money is a ...  positive
..                                                ...       ...
95  daniel daylewis is the most versatile actor al...  positive
96  my guess would be this was originally going to...  negative
97  well i like to watch bad horror bmovies cause ...  negative
98  this is the worst movie i have ever seen as we...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

# Removal of Stop Words

In [29]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [34]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append(' ')

        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return" ".join(x)

In [35]:
df['review'] = df['review'].apply(remove_stopwords)

In [36]:
df

                                               review sentiment
0   one       reviewers   mentioned     watching  ...  positive
1     wonderful little production   filming techni...  positive
2     thought       wonderful way   spend time    ...  positive
3   basically theres   family     little boy jake ...  negative
4   petter matteis love     time   money     visua...  positive
..                                                ...       ...
95  daniel daylewis       versatile actor alive en...  positive
96    guess would       originally going       lea...  negative
97  well   like   watch bad horror bmovies cause  ...  negative
98        worst movie     ever seen   well     wor...  negative
99          mario fan     long       remember     ...  positive

[100 rows x 2 columns]